// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutmeDocumentDataSlicesSlice = never;

/**
 * Content for aboutme documents
 */
interface AboutmeDocumentData {
  /**
   * BackgroundImage field in *aboutme*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.backgroundimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundimage: prismic.ImageField<never>;

  /**
   * BackgoundDescription field in *aboutme*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.backgounddescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  backgounddescription: prismic.KeyTextField;

  /**
   * BackgroundSkills field in *aboutme*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.backgroundskills
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  backgroundskills: prismic.KeyTextField;

  /**
   * Expertise field in *aboutme*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.expertise
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  expertise: prismic.KeyTextField;

  /**
   * ExpertiseDescription field in *aboutme*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.expertisedescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  expertisedescription: prismic.RichTextField;

  /**
   * ExpertiseFrontend field in *aboutme*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.expertisefrontend
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  expertisefrontend: prismic.RichTextField;

  /**
   * ExpertiseBackend field in *aboutme*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.expertisebackend
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  expertisebackend: prismic.RichTextField;

  /**
   * ExpertiseDatabase field in *aboutme*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.expertisedatabase
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  expertisedatabase: prismic.RichTextField;

  /**
   * ExpertiseAddons field in *aboutme*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.expertiseaddons
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  expertiseaddons: prismic.RichTextField;

  /**
   * ExpertiseImage field in *aboutme*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.expertiseimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  expertiseimage: prismic.ImageField<never>;

  /**
   * GoalsImage field in *aboutme*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.goalimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  goalimage: prismic.ImageField<never>;

  /**
   * GoalsDecription field in *aboutme*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.goalsdecription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  goalsdecription: prismic.RichTextField;

  /**
   * Approch field in *aboutme*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.approch
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  approch: prismic.KeyTextField;

  /**
   * ApprochDescription field in *aboutme*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.approchdescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  approchdescription: prismic.RichTextField;

  /**
   * `slices` field in *aboutme*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutmeDocumentDataSlicesSlice>;
}

/**
 * aboutme document from Prismic
 *
 * - **API ID**: `aboutme`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutmeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AboutmeDocumentData>,
    "aboutme",
    Lang
  >;

/**
 * Content for contact documents
 */
interface ContactDocumentData {
  /**
   * email field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * contactNo field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.contactno
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contactno: prismic.KeyTextField;

  /**
   * github Link field in *contact*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.github_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  github_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * dev link field in *contact*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.devlink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  devlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * peer link field in *contact*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.peer_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  peer_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * youtube link field in *contact*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.youtube_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  youtube_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * instagram link field in *contact*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.instagram_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * linkedin link field in *contact*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.linkedin_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * titleName field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.titlename
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titlename: prismic.KeyTextField;
}

/**
 * contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Content for projects documents
 */
interface ProjectsDocumentData {
  /**
   * ProjectImage field in *projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projectimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  projectimage: prismic.ImageField<never>;

  /**
   * TItle field in *projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Decription field in *projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.decription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  decription: prismic.RichTextField;

  /**
   * Technology field in *projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: e.g java, python
   * - **API ID Path**: projects.technology
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  technology: prismic.RichTextField;

  /**
   * type field in *projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type: prismic.KeyTextField;

  /**
   * github field in *projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: link for Repository
   * - **API ID Path**: projects.github
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  github: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * ProjectLink field in *projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to project
   * - **API ID Path**: projects.projectlink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  projectlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectsDocumentData>,
    "projects",
    Lang
  >;

/**
 * Content for slacks documents
 */
interface SlacksDocumentData {
  /**
   * title field in *slacks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slacks.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * icon field in *slacks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slacks.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  icon: prismic.KeyTextField;

  /**
   * color field in *slacks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slacks.color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  color: prismic.KeyTextField;
}

/**
 * slacks document from Prismic
 *
 * - **API ID**: `slacks`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SlacksDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SlacksDocumentData>, "slacks", Lang>;

export type AllDocumentTypes =
  | AboutmeDocument
  | ContactDocument
  | ProjectsDocument
  | SlacksDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutmeDocument,
      AboutmeDocumentData,
      AboutmeDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ProjectsDocument,
      ProjectsDocumentData,
      SlacksDocument,
      SlacksDocumentData,
      AllDocumentTypes,
    };
  }
}
